name: what3words
description: >-
  A Dart library to use the what3words v3 API. This library can either be used
  in native Dart or Flutter applications
version: 3.1.0
homepage: https://github.com/what3words/w3w-dart-wrapper

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  chopper: ^7.0.7+1
  os_detect: ^2.0.0

dev_dependencies:
  chopper_generator: ^7.0.5+1
  pedantic: ^1.11.0
  test: ^1.16.8
